name: PPI
version: 0.900
abstract: Analyze and manipulate Perl code without using perl itself
author: Adam Kennedy<cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  File::Spec: 0.82
  Test::More: 0.47
  Test::ClassAPI: 1.02
requires:
  perl: 5.005
  Class::Inspector: 1.07
  Class::Autouse: 1.12
  Clone: 0.13
  File::Slurp: 9999.04
  List::Util: 1.11
  List::MoreUtils: 0.04
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
