--- 
abstract: Parse, Analyze and Manipulate Perl (without perl)
author: Adam Kennedy <adamk@cpan.org>
build_requires: 
  File::Remove: 0.34
  File::Spec: 0.84
  Test::ClassAPI: 1.03
  Test::More: 0.47
  Test::Object: 0.07
  Test::SubCalls: 1.06
distribution_type: module
generated_by: Module::Install version 0.65_01
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: PPI
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  Clone: 0.22
  Digest::MD5: 2.27
  IO::String: 1.07
  List::MoreUtils: 0.13
  List::Util: 1.18
  Params::Util: 0.10
  Storable: 2.14
  Task::Weaken: 0
  perl: 5.005
version: 1.199_02
