name: PPI
version: 1.003
abstract: Parse, Analyze and Manipulate Perl (without perl)
author: Adam Kennedy <cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  File::Spec: 0.80
  Test::More: 0.47
  Test::ClassAPI: 1.02
requires:
  perl: 5.005
  Clone: 0.17
  List::Util: 1.11
  List::MoreUtils: 0.04
  Params::Util: 0.05
  IO::Scalar: 2.105
no_index:
  directory:
    - t.data
    - inc
generated_by: Module::Install version 0.37
