abstract: Parse, Analyze and Manipulate Perl (without perl)
author: Adam Kennedy <cpan@ali.as>, L<http://ali.as/>
build_requires: 
  File::Remove: 0.22
  File::Spec: 0.84
  Test::ClassAPI: 1.02
  Test::More: 0.47
  Test::SubCalls: 0.01
distribution_type: module
generated_by: Module::Install version 0.63
license: perl
name: PPI
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  Clone: 0.17
  Digest::MD5: 2.27
  IO::String: 1.07
  List::MoreUtils: 0.13
  List::Util: 1.17
  Params::Util: 0.10
  Storable: 2.14
  Task::Weaken: 0
  perl: 5.005
version: 1.116
