# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PPI
version:      0.822
version_from: lib/PPI.pm
installdirs:  site
requires:
    Class::Autouse:                1.04
    Clone:                         0.13
    File::Slurp:                   9999.04
    File::Spec:                    0.82
    List::MoreUtils:               0.04
    List::Util:                    1.11
    Test::ClassAPI:                0.9
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
